{
 "title": "Celery Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Worker State adrian",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "celery_workers_state{worker=\"celery@adrian\"}"
    }
   ]
  },
  {
   "title": "Worker state vultr",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "celery_workers_state{worker=\"celery@vultr.guest\"}"
    }
   ]
  },
  {
   "title": "Task results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "celery_tasks_total",
     "legendFormat": "{{task}} : {{result}}  ( worker : {{worker}} )"
    }
   ]
  },
  {
   "title": "Task cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(celery_tasks_seconds_sum[24h])/rate(celery_tasks_seconds_count[24h])",
     "legendFormat": "task : {{task}}   ( worker : {{worker}} )"
    }
   ]
  },
  {
   "title": "Processed tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "celery_processed_tasks_total", "legendFormat": "worker : {{worker}}" }
   ]
  },
  {
   "title": "Active tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "celery_active_tasks_total", "legendFormat": "worker : {{worker}}" }
   ]
  },
  {
   "title": "Task Information",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 24 },
   "targets": [
    { "expr": "celery_tasks_info_info{}" }
   ]
  }
 ]
}